# They are not part of the build process, dependencies used for testing"

[[IgnoredVulns]]
id = "GHSA-grv7-fg5c-xmjg"
reason = "It is a test dependency"

[[IgnoredVulns]]
id = "GHSA-952p-6rrq-rcjv"
reason = "It is a test dependency"

[[IgnoredVulns]]
id = "GHSA-vpq2-c234-7xj6"
reason = "@tootallnate/once is a test-only dependency (jest@26); fix requires major jest version bump which breaks fixture snapshots"